# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# #############
# main branch
# #############
# GitHub Actions
- target-branch: main
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling:"
  labels:
  - "dependencies"
# Main Go module
- target-branch: main
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "dependencies"
  open-pull-requests-limit: 10
## Update dockerfile
- target-branch: main
  package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling:"
  labels:
  - "dependencies"
# Tools Go module
- target-branch: main
  package-ecosystem: "gomod"
  directory: "/hack/tools"
  schedule:
    interval: "weekly"
    day: "tuesday"
  labels:
  - "dependencies"

# ################
# release branch N
# ################
# GitHub Actions
- target-branch: release-1.10.0
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling:[release-1.10.0]"
  labels:
  - "dependencies"
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
# Main Go module
- target-branch: release-1.10.0
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling:[release-1.10.0]"
  labels:
  - "dependencies"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
## Update dockerfile
- target-branch: release-1.10.0
  package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling:[release-1.10.0]"
  labels:
  - "dependencies"
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
# Tools Go module
- target-branch: release-1.10.0
  package-ecosystem: "gomod"
  directory: "/hack/tools"
  schedule:
    interval: "weekly"
    day: "tuesday"
  commit-message:
    prefix: ":seedling:[release-1.10.0]"
  labels:
  - "dependencies"
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  labels:
  - "dependencies"
