# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto # automatically calculate coverage target - should increase
        threshold: 0.5% # allow for 0.5% reduction without failing
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        if_ci_failed: error
        only_pulls: false
    changes: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes

ignore:
  - "config"
  - "docs"
  - "e2e"
  - "hack"
  - "api/v1alpha1/zz_generated.deepcopy.go"
