#@ load("@ytt:data", "data")

#@ def labels():
app: tanzu-ako-operator
#@ end
#@
#@ def dockerImage():
#@   return  ":".join(["/".join([data.values.imageRegistry, data.values.imageName]),  data.values.imageTag])
#@ end
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels()
  name: ako-operator-controller-manager
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /manager
          image: #@ dockerImage()
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
