apiVersion: network.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
    name: sample-akodeploymentconfig
spec:
    cloudName: Default-Cloud
    serviceEngineGroup: Default-Group
    controller: 10.161.150.145
    controllerVersion: 20.1.6
    adminCredentialRef:
        name: avi-controller-credentials
        namespace: default
    certificateAuthorityRef:
        name: avi-controller-ca
        namespace: default
    dataNetwork:
        name: "VM Network"
        cidr: 10.161.136.0/24
        ipPools:
            - start: 10.161.136.31
              end: 10.161.136.42
              type: V4
    controlPlaneNetwork:
        name: "VM Network 2"
        cidr: 10.192.192.0/19
    extraConfigs:
        primaryInstance: "true"
        apiServerPort: 8080
        fullSyncFrequency: "1800"
        cniPlugin: antrea
        disableStaticRouteSync: "true"
        enableEVH: "false"
        layer7Only: "false"
        vipPerNamespace: "false"
        enableEvents: "false"
        l4Config:
            autoFQDN: "disabled"
            defaultDomain: "default"
        ingress:
            defaultIngressController: false
            disableIngressClass: true
            serviceType: NodePortLocal
            noPGForSNI: false
            shardVSSize: SMALL
            enableMCI: "false"
            nodeNetworkList:
                networkName: "VM Network"
                cidrs:
                - 10.161.20.0/24
                - 10.161.136.0/24
        log:
            logLevel: "INFO"
        networksConfig:
            enableRHI: false
            nsxtT1LR: "NSX-T-T1-ROUTER-ID"
---
apiVersion: v1
kind: Secret
metadata:
    name: avi-controller-credentials
type: Opaque
data:
    username: YWRtaW4=
    password: YWRtaW4hMjM=
---
apiVersion: v1
kind: Secret
metadata:
    name: avi-controller-ca
type: Opaque
data:
    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrRENDQStDZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREJnTVFzd0NRWURWUVFHRXdKVlV6RVQKTUJFR0ExVUVDQXdLUTJGc2FXWnZjbTVwWVRFVU1CSUdBMVVFQnd3TFUyRnVkR0VnUTJ4aGNtRXhFekFSQmdOVgpCQW9NQ2tOdmJuUnliMnhzWlhJeEVUQVBCZ05WQkFNTUNHTmhMbXh2WTJGc01CNFhEVGN3TURFd01UQXdNREF3Ck1Gb1hEVE13TVRJeE5ESXlOREF4TWxvd1lERUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG0KYjNKdWFXRXhGREFTQmdOVkJBY01DMU5oYm5SaElFTnNZWEpoTVJNd0VRWURWUVFLREFwRGIyNTBjbTlzYkdWeQpNUkV3RHdZRFZRUUREQWhqWVM1c2IyTmhiRENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DCmdnSUJBTndRQ2Q1a09hV05kUlQxcmErN2xJMmRjRkN6dnRkSmJsMXBZRmE4eFhsZE11NW9MR093dlFLbkhubmcKcHphNDkyakhlcHdWakxlQThvYnF0MlJaTkh4SUZMZE9nbFZNY3BHSlRiY2RnQWJHaDNDU3VEcHdQMTNOOTVnYQo3b3hlaGZuZEtPRC9MSDk0MVNWaFVZN2FuZXNCempDOVFVcGZ0SWFmaCtkSGI4dklHV0NWanZjK09JYVVJR1NyCnQrZk91alhHVkN1ZDA4NEtLeG9qVXZPU2RPaGdyV2ZVZG9BMUdxU3JmcTY3NVRSWWlMYkF1b0pleXRDSVNCOVYKeFVoYmQvMldGU25YVFZOR1luN3QxUTh1bjE2VExNVTdPQXIrWFgwWTB6alU3V3NsMUdNaExmeDZVWEtPZGUzTgpvVlZFMFdtZlQvZTRDUzFoMkFGMnJoS0N0OVVTL29pM21oOEZFZ1p3dWxrWmNCUlhlV09kc243RWViUzkzTnpDClNXajRhLzhYYUJqZzQ2WEZVUjMrclFreEVoRFM5SURSYTdXQk43OEk1WDJGdzVZL2ZQYVhvYUh4TklxNmF5SmoKUTRDTVgvQnBEcVZoSnhIQTZoa1VUdWhxOWZlc1NTYXVQRkUvSEdhZHA5Q0FCUlV2VHdGczFrMDNRWVBDWXlrOQp4em5aTmY0OXpuaUZySnZ2VDJRc0RUNk54M0pBamVoN3pJNnB0Z25tMWVqN0NiZXhDbi8rL0RicW9rQ05ON09VCktsUzVDcU1kTCswZGE5NnNvQXhEUmM5WE1HV0xsY053UXowc3FKSkNvR1NFU3pVa1haS1JqZ3ZIY05pVDZUV2cKT0Y1OTNaMEVpZTJGcFdFTW80Mlk1MGRhWFFMZDNubDZuTFRjM3J1S2VnNmxlZ2tEQWdNQkFBR2pnYnd3Z2JrdwpIUVlEVlIwT0JCWUVGR2Q3UHZ4T0N4OEVtcWtBc0pTTkd5S09QWW55TUlHSkJnTlZIU01FZ1lFd2Y0QVVaM3MrCi9FNExId1NhcVFDd2xJMGJJbzQ5aWZLaFpLUmlNR0F4Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSURBcEQKWVd4cFptOXlibWxoTVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURVRNQkVHQTFVRUNnd0tRMjl1ZEhKdgpiR3hsY2pFUk1BOEdBMVVFQXd3SVkyRXViRzlqWVd5Q0FRRXdEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FnRUFIbUt1ZWN5UURVY1hGQmZMcnVYU3hUc0ZlTU4yL0w4Z1FSQnAzRU4yV0xVOWFhb2gKZ2E4aVVjYUhOdWlYVUdiSFkrUmhwa2F0N3VKcm9NM0Z5dUhxWko1VWNFVVhkYWNQQ0NzcHlRdDYxbzJVYXFCMQpCZTlxT1c1YkFicFdYalNLUWdkTVFIa0hNaVBUUnF6WnhCMk9QM0pGMGpsZjFRS3JvK0ttNXdCY2xjdm9mTDI0ClduL1FhUFc4bklKUndiOSs5WStpZnE5Q2JtbU5aVFRDa2pudGszbFNVL1luS1NJMy9vbjdvUEtDclF4M2FLeUYKbnIwWVQwZEpYc3JjRnhKL3ZhakZremJYL1Y1VmhrN2g2R1RTaDJFOEtyVVlkeHFhdWNJaFN4VGdvdFYwaWlpUgpRQVRLNGZsWDBBRzI1YVNDSmREV3ROZUdlVWkvZDI4VmlqUXMwM3NtVklkRlVmbzVoUlpQeGJHc1h0RWJTMXh6CnZQN2hSQU8vVXRTaXFhV0JmQU1JWHgvenpwaXJxYTg4RjRxZGQ4VEtFUWdMYkk2cHJIUjNOUDJvSWpPaHBDZWgKOTA5UlJ6a2t4eTJRanNyNVJyYkJhdlZXeFJaUnZPYUduRFVzQzZJMUpxa0RwNU1CbEc1NUxBcUEwRDNnVmVSQwovK3M5OVRCM2w5ZXFqUnRJYmZHU1N5MmRBSUQvYldVRnN0eTFCcWRaZzJNL1kwd1lQTmV1TXgzeXltZlpaRjFyCnU1WnVJRFRPeHJaMDNsYUhCMzJMM21laVROWjFkWGt3SXlIa09HYS9tbTN5SlZ2Y3UrLzlzaGZTdWxncFdiY3IKb3hlYnFVSHQ0dElQbDh2Z3BrR3gxL3Z2eWNta0lwUXEzbEY5OGdTb1NVV3k4bWxPTVJPcUgzYW1HVW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
