name: "React to push to main and release branches"
on:
  push:
    branches:
      - 'main'
      - 'release-**'


jobs:
  lint:
    name: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: Build hack tools for linting
        run: cd hack/tools && make golangci-lint

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install markdown-lint tool
        run: npm install -g markdownlint-cli

      - name: Perform golang code linting
        run: make lint-go

      - name: Perform markdown linting
        run: make lint-markdown

      - name: Perform shell scripts linting with shellcheck
        run: make lint-shell

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Build hack tools for unit testing
        run: cd hack/tools && make controller-gen etcd ginkgo kustomize

      - name: Perform unit tests and output coverage
        run: make cover

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          verbose: true
