name: Trivy Scan

on:
  # Run weekly
  schedule:
  - cron: '0 12 * * 1'
  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    strategy:
      matrix:
        branch:
        - main
        - release-1.10.0
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        persist-credentials: false
        ref: ${{ matrix.branch }}
    - uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # 0.23.0
      with:
        scanners: 'vuln,secret'
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
    - uses: github/codeql-action/upload-sarif@883d8588e56d1753a8a58c1c86e88976f0c23449 # v3.26.3
      with:
        sarif_file: 'trivy-results.sarif'
